version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    networks:
      - localnet
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      #- ./frontend/node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: "production"  # Set to production for relative API URLs
    stdin_open: true
    tty: true
    command: npm start
    networks:
      - localnet
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: trustmeclaude.janczechowski.com
      LETSENCRYPT_HOST: trustmeclaude.janczechowski.com
    ports:
      - "127.0.0.1:8000:80"
    networks:
      - localnet
      - nginx-proxy
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnet
    restart: always

networks:
  localnet:
  nginx-proxy:
    external: true

volumes:
  postgres_data:
