services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    networks:
      - localnet
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      #- ./frontend/node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: "production"  # Set to production for relative API URLs
    stdin_open: true
    tty: true
    command: npm start
    networks:
      - localnet
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: trustmeclaude.janczechowski.com
      LETSENCRYPT_HOST: trustmeclaude.janczechowski.com
    networks:
      - localnet
      - nginx-proxy
    #ports:
    #  - 127.0.0.1:3000:80
    restart: always

  mongodb:
    image: mongo:latest
    networks:
      - localnet
    volumes:
      - mongodb_data:/data/db
    restart: always

networks:
  localnet:
  nginx-proxy:
    external: true

volumes:
  mongodb_data:
